"""Build TCGA-self-derived per-cancer-type table rows for cohorts
with no PCAWG/Alexandrov-2020 row (ACC, DLBC -- see mutation_rates
TODO.md's 2026-08-26 entry for the full investigation).

Unlike every existing row in inclusion/exclusion_signatures_matrix_by_
cancer_type.txt (sourced from Extended Data Figure 5 of Alexandrov
et al. 2020, or from COSMIC's website for post-2020 signatures), these
two rows have a genuinely different provenance: they are built from
this project's own unrestricted SBS decomposition of TCGA's ACC and
DLBC cohorts, using the same prevalence criterion
signature_decomposition.compute_prevalence_overrides already uses to
*override* an existing table row -- applied here from scratch, since
there is no existing row to override. This is not a new method: it is
the same thing Alexandrov 2020 did to build the original table (fit
unrestricted, call what recurs "present"), just applied to TCGA data
for the two cohorts PCAWG happened not to cover.

A signature is called "included" (kept in the fit) if it has nonzero
exposure in at least MIN_PREVALENCE of the cohort's adequately-powered
(burden >= MIN_BURDEN) samples, after first dropping samples flagged
by the same treatment-signature-load criterion
qc.flag_treatment_signature_samples uses (order matters here for the
same reason it matters in the real two-pass mechanism: a
treatment-contaminated tumor about to be dropped shouldn't inflate
another signature's apparent prevalence). All three thresholds
(MIN_BURDEN, TREATMENT_LOAD_THRESHOLD, MIN_PREVALENCE) are this
project's own provisional choices, not literature-derived -- see the
"threshold sensitivity analysis" item in mutation_rates TODO.md.

Input: local snapshots of each cohort's unrestricted-fit
Assignment_Solution_Activities.txt (data-raw/self_derived_cancer_type_
rows/<CODE>_unrestricted_activities.txt), generated by
tcga_analysis/code/run_unrestricted_signature_decomposition.py and
copied here for reproducibility/audit -- this script does not have
network or gauss access to regenerate them itself.

Output: appends one row per cohort to both
src/sigmutsel/data/{inclusion,exclusion}_signatures_matrix_by_
cancer_type.txt, in the same 60-signature column order as the
existing rows. Idempotent: refuses to run if a row for that cohort
already exists (re-run after deleting the row by hand if inputs
change).

Usage: python data-raw/build_self_derived_cancer_type_rows.py
"""

from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
INPUT_DIR = HERE / "self_derived_cancer_type_rows"
DATA_DIR = HERE / ".." / "src" / "sigmutsel" / "data"
EXCLUSION_TABLE = (
    DATA_DIR / "exclusion_signatures_matrix_by_cancer_type.txt"
)
INCLUSION_TABLE = (
    DATA_DIR / "inclusion_signatures_matrix_by_cancer_type.txt"
)

TREATMENT_ASSOCIATED_SIGNATURES = {
    "SBS11",
    "SBS113",
    "SBS17b",
    "SBS25",
    "SBS31",
    "SBS32",
    "SBS35",
    "SBS86",
    "SBS87",
    "SBS90",
    "SBS99",
}
ARTIFACT_SIGNATURES = {
    "SBS27",
    "SBS43",
    "SBS45",
    "SBS46",
    "SBS47",
    "SBS48",
    "SBS49",
    "SBS50",
    "SBS51",
    "SBS52",
    "SBS53",
    "SBS54",
    "SBS55",
    "SBS56",
    "SBS57",
    "SBS58",
    "SBS59",
    "SBS60",
    "SBS95",
}

MIN_BURDEN = 100
TREATMENT_LOAD_THRESHOLD = 0.2
MIN_PREVALENCE = 0.15

# (TCGA code, PCAWG-column label, human description) -- description
# deliberately comma-free so it doesn't need quoting in either table
# file's existing (inconsistent) quoting convention.
COHORTS = [
    (
        "ACC",
        "ACC-TCGA-self-derived",
        (
            "adrenocortical carcinoma; no PCAWG row; "
            "see mutation_rates TODO.md 2026-08-26"
        ),
    ),
    (
        "DLBC",
        "DLBC-TCGA-self-derived",
        (
            "diffuse large B-cell lymphoma; no PCAWG row; "
            "see mutation_rates TODO.md 2026-08-26"
        ),
    ),
]


def _signature_columns(table_path):
    header = pd.read_csv(
        table_path, sep="\t", nrows=0
    ).columns.tolist()
    return header[4:]


def _decide_inclusion(activities_path, sig_columns):
    df = pd.read_csv(activities_path, sep="\t", index_col=0)
    totals = df.sum(axis=1)

    treat_cols = [
        c for c in TREATMENT_ASSOCIATED_SIGNATURES if c in df.columns
    ]
    treat_totals = (
        df[treat_cols].sum(axis=1)
        if treat_cols
        else pd.Series(0.0, index=df.index)
    )
    treatment_load = (treat_totals / totals.replace(0, pd.NA)).astype(
        float
    )
    treatment_load[totals < MIN_BURDEN] = float("nan")
    survivors = df.index[~(treatment_load > TREATMENT_LOAD_THRESHOLD)]

    pool = df.loc[df.index.isin(survivors) & (totals >= MIN_BURDEN)]
    n_pool = len(pool)

    included = set()
    for sig in sig_columns:
        if sig in ARTIFACT_SIGNATURES:
            # Irrelevant to the fit (resolve_exclusion_list always
            # strips artifacts from a table's own contribution
            # regardless of this value), but write "excluded" for
            # readability -- matches how artifact columns read for
            # every other row in these tables.
            continue
        if sig not in df.columns:
            continue
        prevalence = (pool[sig] > 0).mean() if n_pool > 0 else 0.0
        if prevalence >= MIN_PREVALENCE:
            included.add(sig)

    return included, n_pool


def _append_row(
    table_path, pcawg_label, tcga_code, n, description, values
):
    # Read/write in binary mode and preserve whichever line ending
    # the file already uses (the two tables are inconsistent with
    # each other here -- exclusion uses LF, inclusion uses CRLF) so
    # appending two rows doesn't rewrite every other line's ending
    # and pollute the diff.
    existing = table_path.read_bytes()
    if f"\t{tcga_code}\t".encode() in existing:
        raise RuntimeError(
            f"{table_path.name} already has a row for {tcga_code} -- "
            "delete it by hand first if inputs changed."
        )
    newline = b"\r\n" if b"\r\n" in existing else b"\n"
    if not existing.endswith(newline):
        existing += newline
    row = "\t".join(
        [pcawg_label, tcga_code, str(n), description]
        + [str(v) for v in values]
    )
    table_path.write_bytes(existing + row.encode() + newline)


def main():
    sig_columns = _signature_columns(EXCLUSION_TABLE)
    assert _signature_columns(INCLUSION_TABLE) == sig_columns

    for tcga_code, pcawg_label, description in COHORTS:
        activities_path = (
            INPUT_DIR / f"{tcga_code}_unrestricted_activities.txt"
        )
        included, n_pool = _decide_inclusion(
            activities_path, sig_columns
        )
        print(
            f"{tcga_code}: {len(included)}/{len(sig_columns)} signatures "
            f"included (n_pool={n_pool} adequately-powered samples): "
            f"{sorted(included)}"
        )

        exclusion_values = [
            0 if sig in included else 1 for sig in sig_columns
        ]
        inclusion_values = [
            1 if sig in included else 0 for sig in sig_columns
        ]

        _append_row(
            EXCLUSION_TABLE,
            pcawg_label,
            tcga_code,
            n_pool,
            description,
            exclusion_values,
        )
        _append_row(
            INCLUSION_TABLE,
            pcawg_label,
            tcga_code,
            n_pool,
            description,
            inclusion_values,
        )
        print(
            f"  appended to {EXCLUSION_TABLE.name} and {INCLUSION_TABLE.name}"
        )


if __name__ == "__main__":
    main()
